// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hub struct {
	ID      int    `json:"id"`
	Country string `json:"country"`
	Name    string `json:"name"`
	Address string `json:"address"`
	State   string `json:"state"`
}

type NewHub struct {
	Country string `json:"country"`
	Name    string `json:"name"`
	Address string `json:"address"`
	State   string `json:"state"`
}
